config/routes.rb
ActionController::Routing::Routes.draw do |map|
  
  map.root :controller => 'catalog', :action => 'index'
  
  map.about 'about/', :controller => 'about', :action => 'index'
  map.search 'catalog/search', :controller => 'catalog', :action => 'search'
  map.latest 'catalog/latest', :controller => 'catalog', :action => 'latest'
  map.rss_feed 'catalog/rss', :controller => 'catalog', :action => 'rss', :format => 'xml'
  
  map.namespace('admin') do |admin|
    admin.resources :authors,  :controller => 'author'
    admin.resources :publishers, :controller => 'publisher'
    admin.resources :books, :controller => 'books', :collection => {:list => :get}
  end
  
  map.resources 'catalog'
  
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

app/models/author.rb
class Author < ActiveRecord::Base
  
  has_and_belongs_to_many :books
  
  validates_presence_of :first_name
  validates_presence_of :last_name
  
  def name
    "#{first_name} #{last_name}"
  end
  
end

app/models/book.rb
class Book < ActiveRecord::Base
  
  has_and_belongs_to_many :authors
  belongs_to :publisher
  
  acts_as_ferret :fields => [:title, :author_names]
  
  file_column :cover_image
  
  validates_presence_of :title, :in => 1..255
  validates_presence_of :publisher
  validates_presence_of :authors
  validates_presence_of :published_at
  validates_numericality_of :page_count, :only_integer => true
  validates_numericality_of :price
  validates_format_of :isbn, :with => /[0-9\-xX]{10,13}/
  validates_uniqueness_of :isbn
  
  def author_names
    self.authors.map do |a|
      a.name
    end.join(', ') rescue ''
  end
  
  def self.latest
    find :all, :limit => 10, :order => 'books.id DESC',
      :include => [:authors, :publisher]
  end
  
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  
  has_many :books
  
  validates_length_of :name, :in => 2..255
  validates_uniqueness_of :name
  
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
    @page_title = 'About Emporium'
  end

end

app/controllers/admin/author_controller.rb
class Admin::AuthorController < ApplicationController
  
  def new
    @author = Author.new
    @page_title = 'Create new author'
  end

  def create
    @author = Author.new(params[:author])
    if @author.save
      flash[:notice] = "Author #{@author.name} was successfully created."
      redirect_to :action => 'index'
    else
      @page_title = 'Create new author'
      render :action => 'new'
    end
  end

  def edit
    @author = Author.find(params[:id])
    @page_title = 'Edit author'
  end

  def update
    @author = Author.find(params[:id])
    if @author.update_attributes(params[:author])
      flash[:notice] = 'Author was successfully updated.'
      redirect_to :action => 'show', :id => @author
    else
      @page_title = 'Edit author'
      render :action => 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])
    flash[:notice] = "Successfully deleted author #{@author.name}"
    @author.destroy
    redirect_to :action => 'index'
  end

  def show
    @author = Author.find(params[:id])
    @page_title = @author.name
  end

  def index
    @authors = Author.find(:all)
    @page_title = 'Listing authors'
  end

end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  
  def index
    list
    render :action => 'list'
  end
  
  def list
    @page_title = 'Listing books'
    sort_by = params[:sort_by]
    @books = Book.paginate :per_page => 10, :page => params[:page], :order => sort_by
  end
  
  def show
    @book = Book.find(params[:id])
    load_data
    @page_title = "#{@book.title}"
  end
  
  def new
    load_data
    @book = Book.new
  end
  
  def edit
    @book = Book.find(params[:id])
    load_data
    @page_title = "Editing book #{@book.title}"
  end
  
  def create
    @book = Book.new(params[:book])
    
    if @book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to :action => 'list'
    else
      load_data
      render :action => 'new'
    end
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(params[:book])
      flash[:notice] = 'Book was successfully updated.'
      redirect_to :action => 'show', :id => @book
    else
      load_data
      render :action => 'edit'
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    
    redirect_to :action => 'list'
  end
  
  private
    
    def load_data
      @authors = Author.find(:all)
      @publishers = Publisher.find(:all)
    end
  
end

app/controllers/admin/publisher_controller.rb
class Admin::PublisherController < ApplicationController
  def index
    list
    render :action => 'list'
  end

  # GETs should be safe (see http://www.w3.org/2001/tag/doc/whenToUseGet.html)
  #verify :method => :post, :only => [ :destroy, :create ],
  #       :redirect_to => { :action => :list }

  def list
    #@publisher_pages, @publishers = paginate :publishers, :per_page => 10
    @publishers = Publisher.find(:all)
  end

  def show
    @publisher = Publisher.find(params[:id])
    @page_title = @publisher.name
  end

  def new
    @publisher = Publisher.new
  end

  def create
    @publisher = Publisher.new(params[:publisher])
    if @publisher.save
      flash[:notice] = 'Publisher was successfully created.'
      redirect_to :action => 'list'
    else
      render :action => 'new'
    end
  end

  def edit
    @publisher = Publisher.find(params[:id])
  end

  def update
    @publisher = Publisher.find(params[:id])
    if @publisher.update_attributes(params[:publisher])
      flash[:notice] = 'Publisher was successfully updated.'
      redirect_to admin_publisher_path(@publisher)
    else
      render :action => 'edit'
    end
  end

  def destroy
    @publisher = Publisher.find(params[:id])
    flash[:notice] = "Successfully deleted publisher #{@publisher.name}"
    @publisher.destroy
    redirect_to :action => 'list'
  end
end

app/controllers/application_controller.rb
# Filters added to this controller apply to all controllers in the application.
# Likewise, all the methods added will be available for all controllers.

class ApplicationController < ActionController::Base
  helper :all # include all helpers, all the time
  protect_from_forgery # See ActionController::RequestForgeryProtection for details

  # Scrub sensitive parameters from your log
  # filter_parameter_logging :password
end

app/controllers/catalog_controller.rb
class CatalogController < ApplicationController
  
  def index
    @page_title = 'Book list'
    @books = Book.paginate :per_page => per_page, :page => params[:page],
      :include => [:authors, :publisher], :order => 'books.id DESC'
  end

  def show
    @book = Book.find(params[:id]) rescue nil
    return render(:text => 'Not Found', :status => 404) unless @book
    @page_title = @book.title
  end

  def search
    @page_title = 'Search'
    if params[:commit] == 'Search' || params[:q]
      @books = Book.find_with_ferret(params[:q].to_s.upcase)
      unless @books.size > 0
        flash.now[:notice] = 'No books found matching your criteria'
      end
    end
  end

  def latest
    @page_title = 'Latest books'
    @books = Book.latest
  end
  
  def rss
    latest
    
    respond_to do |format|
      format.xml { render :layout => false }
    end
  end
  
  protected
    
    cattr_reader :per_page
    @@per_page = 10

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin/author_helper.rb
module Admin::AuthorHelper
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
  def author_list(book)
    book.authors.collect{|author| author.name}.join(', ')
  end
end

app/helpers/admin/publisher_helper.rb
module Admin::PublisherHelper
end

app/helpers/application_helper.rb
# Methods added to this helper will be available to all templates in the application.
module ApplicationHelper
end

app/helpers/catalog_helper.rb
module CatalogHelper
end

app/views/about/index.html.erb
<p>Online bookstore located in downtown Manhattan, New York</p>
<h2>Mailing Address</h2>
<address>
  Emporium<br />
  P.O. Box 0000<br />
  Grand Cayman, Cayman Islands<br />
</address>

app/views/admin/author/_author.html.erb
<tr>
  <td><%= link_to author.name, admin_author_path(author) %></td>
  <td><%= link_to 'Edit', edit_admin_author_path(author) %></td>
  <td>
    <%= link_to 'Delete', admin_author_path(author), :method => :delete,
        :confirm => "Are you sure you want to delete author #{author.name}?" %>
  </td>
</tr>

app/views/admin/author/_author_form.html.erb
<%= error_messages_for 'author' %>

<p>
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name%>
</p>
<p>
  <%= f.label :last_name %><br />
  <%= f.text_field :last_name %>
</p>

app/views/admin/author/edit.html.erb
<% form_for @author, :url => {:action => 'update'} do |f| %>
  <%= render :partial => 'author_form', :locals => {:f => f} %>
  <%= submit_tag 'Edit' %>
<% end %>

<%= link_to 'Show', admin_author_path(@author) %> | 
<%= link_to 'Back', admin_authors_path %>

app/views/admin/author/index.html.erb
<table id="index_item_list">
  <tr>
    <th>Name</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>

  <%= render :partial => 'author', :collection => @authors %>
</table>

<p><%= link_to 'Add a new author', new_admin_author_path %></p>

app/views/admin/author/new.html.erb
<% form_for @author, :url => {:action => 'create'} do |f| %>
  <%= render :partial => 'author_form', :locals => {:f => f} %>
  <%= submit_tag 'Create' %>
<% end %>

<%= link_to 'Back', admin_authors_path %>

app/views/admin/author/show.html.erb
<dl>
  <dt>First name</dt>
  <dd><%= @author.first_name %></dd>
  <dt>Last name</dt>
  <dd><%= @author.last_name %></dd>
</dl>

<p>
  <%= link_to 'Edit', edit_admin_author_path(@author) %> | 
  <%= link_to 'Back', admin_authors_path %>
</p>

app/views/admin/books/_book_form.html.erb
<p>
  <%= f.label :title %><br />
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :publisher %><br />
  <%= f.collection_select :publisher_id, @publishers, :id, :name %>
</p>
<p>
  <%= f.label :authors %><br />
  <%= select_tag 'book[author_ids][]',
        options_from_collection_for_select(@authors, :id, :name,
          @book.authors.collect { |author| author.id }),
        {:multiple => true, :size => 5} %>
</p>
<p>
  <%= f.label :published_at %><br />
  <%= f.datetime_select :published_at %>
</p>
<p>
  <%= f.label :isbn %><br />
  <%= f.text_field :isbn %>
</p>
<p>
  <%= f.label :blurb %><br />
  <%= f.text_area :blurb %>
</p>
<p>
  <%= f.label :price %><br />
  <%= f.text_field :price %>
</p>
<p>
  <%= f.label :page_count %><br />
  <%= f.text_field :page_count %>
</p>
<p>
  <%= f.label :cover_image %><br />
  <%= file_column_field 'book', 'cover_image' %>
</p>

app/views/admin/books/edit.html.erb
<% form_for @book, :url => {:action => 'update'}, :html => {:multipart => true} do |f| %>
  <%= f.error_messages %>
  <%= render :partial => 'book_form', :locals => {:f => f}%>
  <p>
    <%= f.submit 'Update' %>
  </p>
<% end %>

<%= link_to 'Show', admin_book_path(@book) %> |
<%= link_to 'Back', admin_books_path %>

app/views/admin/books/list.html.erb
<table id="index_item_list">
  <tr>
    <th><a href="?sort_by=publisher_id">Publisher</a></th>
    <th><a href="?sort_by=title">Title</a></th>
    <th><a href="?sort_by=isbn">ISBN</a></th>
    <th colspan="3"></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= h book.publisher.name %></td>
    <td><%= h book.title %></td>
    <td><%= h book.isbn %></td>
    <td><%= link_to 'Show', admin_book_path(book) %></td>
    <td><%= link_to 'Edit', edit_admin_book_path(book) %></td>
    <td>
      <%= link_to 'Delete', admin_book_path(book), :confirm => 'Are you sure?', :method => :delete %>
    </td>
  </tr>
<% end %>
</table>

<%= will_paginate @books %>

<br />

<%= link_to 'New book', new_admin_book_path %>

app/views/admin/books/new.html.erb
<h1>New book</h1>

<% form_for @book, :url => {:action => 'create'}, :html => {:multipart => true} do |f| %>
  <%= f.error_messages %>
  <%= render :partial => 'book_form', :locals => {:f => f} %>
  <p>
    <%= f.submit 'Create' %>
  </p>
<% end %>

<%= link_to 'Back', admin_books_path %>

app/views/admin/books/show.html.erb
<dl>
  <dt>Title</dt>
  <dd><%= h @book.title %></dd>
  <dt>Publisher</dt>
  <dd><%= h @book.publisher.name %></dd>
  <dt>Published at</dt>
  <dd><%= h @book.published_at.strftime("%m%d%Y at %I:%m%p") %></dd>
  <dt>Authors</dt>
  <dd><%= h author_list(@book) %></dd>
  <dt>ISBN</dt>
  <dd><%= h @book.isbn %></dd>
  <dt>Blurb</dt>
  <dd><%= textilize @book.blurb %></dd>
  <dt>Price</dt>
  <dd><%= h @book.price %></dd>
  <dt>Page count</dt>
  <dd><%= h @book.page_count %></dd>
  <dt>Cover image</dt>
  <% if @book.cover_image.nil? %>
    <dd>N/A</dd>
  <% else %>
    <dd><%= image_tag url_for_file_column(:book, :cover_image) %></dd>
  <% end %>
</dl>
<p>
  <%= link_to 'Edit', edit_admin_book_path(@book) %> | 
  <%= link_to 'Back', admin_books_path %>
</p>

app/views/admin/publisher/_publisher_form.html.erb
<%= error_messages_for 'publisher' %>

<p>
  <%= f.label :name %><br />
  <%= f.text_field :name  %>
</p>
<br />

app/views/admin/publisher/edit.html.erb
<h1>Editing publisher</h1>

<% form_for @publisher, :url => {:action => 'update'} do |f| %>
  <%= render :partial => 'publisher_form', :locals => {:f => f} %>
  <%= submit_tag 'Edit' %>
<% end %>

<%= link_to 'Show', admin_publisher_path(@publisher) %> |
<%= link_to 'Back', admin_publishers_path %>

app/views/admin/publisher/list.html.erb
<h1>Listing publishers</h1>

<table id="index_item_list">
  <tr>
    <th>Name</th>
    <th colspan="3">&nbsp;</th>
  </tr>
  
<% for publisher in @publishers %>
  <tr>
    <td><%=h publisher.name %></td>
    <td><%= link_to 'Show', admin_publisher_path(publisher) %></td>
    <td><%= link_to 'Edit', edit_admin_publisher_path(publisher) %></td>
    <td>
      <%= link_to 'Delete ', admin_publisher_path(publisher), :confirm => 'Are you sure?', 
          :method => :delete %>
    </td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New publisher', new_admin_publisher_path %>

app/views/admin/publisher/new.html.erb
<h1>New publisher</h1>

<% form_for @publisher, :url => {:action => 'create'} do |f| %>
  <%= render :partial => 'publisher_form', :locals => {:f => f} %>
  <%= submit_tag "Create" %>
<% end %>

<%= link_to 'Back', admin_publishers_path %>

app/views/admin/publisher/show.html.erb
<dl>
  <dt>Name</dt>
  <dd><%= @publisher.name %></dd>
</dl>

<%= link_to 'Edit', edit_admin_publisher_path(@publisher) %> | 
<%= link_to 'Back', admin_publishers_path %>

app/views/catalog/_books.html.erb
<dl id='books'>
  <% for book in @books %>
    <dt><%= link_to book.title, catalog_path(book) %></dt>
    <% for author in book.authors %>
      <dd><%= author.last_name %>, <%= author.first_name %></dd>
    <% end %>
      <dd><%= pluralize(book.page_count, 'page') %></dd>
      <dd>Price: $<%= sprintf("%.2f", book.price) %></dd>
      <dd><small>Publisher: <%= book.publisher.name %></small></dd>
  <% end %>
</dl>

app/views/catalog/_search_box.html.erb
<% form_tag({:action => 'search'}, {:method => 'get'}) do %>
  <%= text_field_tag :q %>
  <%= submit_tag 'Search' %>
<% end %>

app/views/catalog/index.html.erb
<p><%= link_to 'Search', search_path %></p>

<%= render :partial => 'books' %>

<%= will_paginate @books %>

app/views/catalog/latest.html.erb
<%= render :partial => 'books' %>

app/views/catalog/search.html.erb
<%= render :partial => 'search_box' %>

<% if @books %>
  <p>
    You search "<%= params[:q] %>" produced <%= pluralize(@books.size, 'result') %>:
  </p>
  <%= render :partial => 'books' %>
<% end %>

app/views/catalog/show.html.erb
<h2>by <%= @book.authors.map{|a| a.name}.join(', ') %></h2>
<%= image_tag url_for_file_column(:book, :cover_image) unless @book.cover_image.blank? %>
<dl>
  <dt>Price</dt>
  <dd>$<%= sprintf("%0.2f", @book.price) %></dd>
  <dt>Page count</dt>
  <dd><%= @book.page_count %></dd>
  <dt>Publisher</dt>
  <dd><%= @book.publisher.name %></dd>
  <dt>Blurb</dt>
  <dd><%= @book.blurb %></dd>
</dl>

<p>
  <%= link_to 'Back to Catalog', catalog_index_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">  
<head>
  <title><%= @page_title || 'Emporium' %></title>

  <%= stylesheet_link_tag "style" %>
  <%= auto_discovery_link_tag(:rss, {:controller => 'catalog', :action => 'rss'}) %>
</head>
<body>

<div id="header">
  <h1 id="logo">Emporium&trade;</h1>
  <h2 id="slogan">Books on Rails</h2>
</div>

<div id="menu">
  <ul>
    <li><a href="/admin/author">Authors</a>&nbsp;|&nbsp;</li>
    <li><a href="/admin/publisher">Publishers</a>&nbsp;|&nbsp;</li>
    <li><a href="/admin/books">Books</a>&nbsp;|&nbsp;</li>
    <li><a href="/">Catalog</a>&nbsp;|&nbsp;</li>
    <li><a href="/about">About</a>&nbsp;</li>
  </ul>
</div>
  
<div id="content">
  <%= "<h1>#{@page_title}</h1>" if @page_title %>
  <% if flash[:notice] %>
    <div id="notice">
      <%= flash[:notice] %>
    </div>
  <% end %>
  <%= yield %>
</div>

<div id="footer">
  &copy; 1995-2009 Emporium
</div>
  
</body>
</html>